apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kolibri.fullname" . }}
  labels:
    {{- include "kolibri.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kolibri.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kolibri.labels" . | nindent 8 }}
        app.kubernetes.io/component: app
    spec:
      containers:
        - name: kolibri
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "kolibri.fullname" . }}-config
          {{- if or .Values.oidc.enabled .Values.extraEnv }}
          env:
            {{- if .Values.oidc.enabled }}
            - name: KOLIBRI_OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.oidc.existingSecret }}
                  key: {{ .Values.oidc.clientSecretKey }}
            {{- end }}
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: kolibri-data
              mountPath: {{ .Values.persistence.mountPath }}
          {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: kolibri-data
          persistentVolumeClaim:
            claimName: {{ include "kolibri.fullname" . }}
      {{- end }}
