apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-homelab
  labels:
    app.kubernetes.io/part-of: kids-games
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/name: external-secrets
spec:
  provider:
    vault:
      server: https://vault.family.home.arpa
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: kids-games-eso
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
      tls:
        insecureSkipVerify: true
