apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "virtualtabletop.fullname" . }}
  labels:
    {{- include "virtualtabletop.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "virtualtabletop.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "virtualtabletop.labels" . | nindent 8 }}
        app.kubernetes.io/component: app
    spec:
      containers:
        - name: virtualtabletop
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
