{{- if .Values.oauth2Proxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "virtualtabletop.fullname" . }}-oauth2-proxy
  labels:
    {{- include "virtualtabletop.labels" . | nindent 4 }}
    app.kubernetes.io/component: oauth2-proxy
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.oauth2Proxy.port }}
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "virtualtabletop.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: oauth2-proxy
{{- end }}
