apiVersion: v1
kind: Service
metadata:
  name: {{ include "virtualtabletop.fullname" . }}
  labels:
    {{- include "virtualtabletop.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "virtualtabletop.selectorLabels" . | nindent 4 }}
