apiVersion: v1
kind: Secret
metadata:
  name: moodle-secrets
  namespace: games-moodle
  labels:
    app.kubernetes.io/part-of: kids-games
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/name: moodle
stringData:
  moodle-password: CHANGE_ME
  smtp-password: CHANGE_ME
---
apiVersion: v1
kind: Secret
metadata:
  name: moodle-oidc
  namespace: games-moodle
  labels:
    app.kubernetes.io/part-of: kids-games
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/name: moodle
stringData:
  MOODLE_OIDC_CLIENT_SECRET: CHANGE_ME  # use the homelab-apps client secret
---
apiVersion: v1
kind: Secret
metadata:
  name: moodle-mariadb
  namespace: games-moodle
  labels:
    app.kubernetes.io/part-of: kids-games
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/name: moodle
stringData:
  mariadb-root-password: CHANGE_ME
  mariadb-password: CHANGE_ME
