apiVersion: v1
kind: Secret
metadata:
  name: openedx-secrets
  namespace: games-openedx
  labels:
    app.kubernetes.io/part-of: kids-games
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/name: openedx
stringData:
  OPENEDX_SUPERUSER_PASSWORD: CHANGE_ME
  MYSQL_ROOT_PASSWORD: CHANGE_ME
  SMTP_PASSWORD: CHANGE_ME
