apiVersion: v1
kind: Secret
metadata:
  name: virtualtabletop-oauth2-proxy
  namespace: games-virtualtabletop
  labels:
    app.kubernetes.io/part-of: kids-games
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/name: virtualtabletop
stringData:
  client-secret: CHANGE_ME  # use the homelab-apps client secret
  cookie-secret: CHANGE_ME  # 16, 24, or 32 bytes (32 chars recommended)
