apiVersion: v1
kind: Secret
metadata:
  name: wordpress-mariadb
  namespace: games-wordpress-h5p
  labels:
    app.kubernetes.io/part-of: kids-games
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/name: wordpress-h5p
stringData:
  mariadb-root-password: CHANGE_ME
  mariadb-password: CHANGE_ME
